"""Default token budgets for context and memory management."""

DEFAULT_CHARS_PER_TOKEN = 4
DEFAULT_MAX_PROMPT_TOKENS = 128_000
DEFAULT_MEMORY_TOKEN_LIMIT = 16_000
DEFAULT_SUMMARY_TOKEN_LIMIT = 8_000
DEFAULT_RAW_HISTORY_TOKEN_LIMIT = 128_000
DEFAULT_RAW_HISTORY_TARGET_TOKENS = 80_000
DEFAULT_KEEP_RECENT_MESSAGES = 40
DEFAULT_MAX_COMPRESSION_ROUNDS = 2
